k <- read.table("power.txt",sep = ";")
lam <- subset(k,V1=="1/2/2007")
kam <- subset(k,V1=="2/2/2007")
jose <- rbind(lam,kam)
colnames(jose) <- c("Date","Time","Global active power","Global reactive power","Voltage","Global intensity","Sub metering 1","Sub metering 2","Sub metering 3")
rownames(jose) <- c(1:2880)

jose$Date <- as.Date(jose$Date,format="%d/%m/%Y")
jose$datetime <- as.POSIXct(paste(jose$Date,jose$Time), format="%Y-%m-%d %H:%M:%S")
png(filename = "plot4.png",height = 480,width = 480,bg="transparent")
par(mfrow=c(2,2))
plot(jose$datetime,jose$`Global active power`,ylab = "Global Active Power",type = "n")
lines(jose$datetime,jose$`Global active power`)
plot(jose$datetime,jose$Voltage,ylab = "Voltage",xlab = "datetime",type = "n")
lines(jose$datetime,jose$Voltage)
plot(jose$datetime,jose$`Sub metering 1`,type = "n",ylab = "Energy Sub Metering")
lines(jose$datetime,jose$`Sub metering 1`,type = "l")
lines(jose$datetime,jose$`Sub metering 2`,col="red",type = "l")
lines(jose$datetime,jose$`Sub metering 3`,col="blue",type = "l")
legend("topright",c("sub metering1","sub metering 2","sub metering 3"),col=c("black","red","blue"),lwd=2.5)
plot(jose$datetime,jose$`Global reactive power`,type = "n")
lines(jose$datetime,jose$`Global reactive power`)
dev.off()